import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import LenisScroll from "./_components/LenisScroll";
import Navbar from "./_components/Navbar";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisScroll>
          <Navbar />
          {children}
        </LenisScroll>
      </body>
    </html>
  );
}
